[project]
name = "5mat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "lark-parser>=0.12.0",
    "matplotlib==3.10.7",
    "networkx==3.5",
]
